---
version: '3'
services:
    db:
        image: mysql
        container_name: lifelog_db
        volumes:
            - ./.data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    web:
        build:
            context: .
            dockerfile: docker/web/Dockerfile
        container_name: lifelog_web
        links:
            - db:drupal_db
        volumes:
            - ./drupal:/var/www/drupal
        ports:
            - 8100:80
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_HOSTNAME: ${MYSQL_HOSTNAME}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_PORT: ${MYSQL_PORT}
            MYSQL_USER: ${MYSQL_USER}
            LIFELOG_OPENWEATHER_APPID: ${LIFELOG_OPENWEATHER_APPID}
            LIFELOG_OPENWEATHER_ZIP: ${LIFELOG_OPENWEATHER_ZIP}
            LIFELOG_OPENWEATHER_COUNTY_CODE: ${LIFELOG_OPENWEATHER_COUNTY_CODE}
